dockerfile and backupApplication image
redhat-ztp/openshift-ai-image-backup pull request #3
Opened 2021-11-03 12:26 UTC by sabbir-47

2021-11-03 14:44 UTC, yrobla requested changes

2021-11-03 14:44 UTC, yrobla commented on Dockerfile
> +RUN yum -y install skopeo && yum -y install wget && yum -y install jq
you can just do it on the same line "yum -y install skopeo wget jq"

2021-11-03 14:44 UTC, yrobla commented on Dockerfile
> +ENV VERSION="v1.22.0"
change to CRICTL_VERSION, so we know what's this version for

2021-11-24 19:10 UTC, donpenney approved these changes
lgtm

2021-11-25 13:54 UTC, merged